'use client';
import {useEffect,useRef,useState} from 'react';
import {Guitar,Play,Pause,Volume2,Check,BookOpen,Headphones,MessageCircle,Timer,Download,Upload,Settings2,RotateCcw,Music2,ExternalLink,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import SongRecording from '@/components/song-recording';
import {songs,warmups,noteNames,chordShapes,SongId,Step} from '@/lib/curriculum';
import {context,playNotes,click,tone,stopDemo} from '@/lib/audio';
type Track={position:number;completed:string[];review:string[];answers:Record<string,number>;playing:Record<string,string>;tempos:Record<string,number>};
type Saved={version:1;song:SongId;tracks:Record<SongId,Track>;warm:number;notes:string};
const blankTrack=():Track=>({position:0,completed:[],review:[],answers:{},playing:{},tempos:{}});
const initial=():Saved=>({version:1,song:'royal',tracks:{royal:blankTrack(),hungersite:blankTrack()},warm:0,notes:''});
const KEY='guitar-practice-v1';
function valid(data:unknown):data is Saved{const d=data as Saved;return !!d&&d.version===1&&['royal','hungersite'].includes(d.song)&&typeof d.notes==='string'&&Number.isInteger(d.warm)&&d.warm>=0&&d.warm<4&&['royal','hungersite'].every(s=>{const t=d.tracks?.[s as SongId];return t&&Number.isInteger(t.position)&&t.position>=0&&t.position<25&&Array.isArray(t.completed)&&t.completed.every(x=>typeof x==='string')&&Array.isArray(t.review)&&t.review.every(x=>typeof x==='string')&&t.answers&&Object.values(t.answers).every(x=>Number.isInteger(x)&&x>=0&&x<3)&&t.playing&&Object.values(t.playing).every(x=>x==='ready'||x==='review')&&t.tempos&&Object.values(t.tempos).every(x=>Number.isFinite(x)&&x>=35&&x<=180)})}
function Fretboard({step,root,rootMidi,hidden}:{step:Step;root:string;rootMidi:number;hidden:boolean}){const tuning=[64,59,55,50,45,40],strings=['e','B','G','D','A','E'];const frets= root==='D'?[7,8,9,10,11,12]:[1,2,3,4,5,6];return <div className="neckwrap"><div className="neck" role="group" aria-label={`${root} fretboard, highest string first`}><div className="frethead"><span/> {frets.map(f=><span key={f}>{f}</span>)}</div>{tuning.map((open,s)=><div className="stringrow" key={s}><strong>{strings[s]}</strong>{frets.map(f=>{const degree=(open+f-rootMidi+120)%12,index=step.notes?.indexOf(degree)??-1;return <div className="fretcell" key={f}>{index>=0?<button className={`notedot ${degree===0?'rootdot':''}`} aria-label={`${strings[s]} string fret ${f}, ${hidden?'note hidden':noteNames[(open+f)%12]}`} onClick={()=>playNotes([open+f],70).catch(()=>{})}>{hidden?'•':noteNames[(open+f)%12]}<small>{hidden?'':step.degrees?.[index]}</small></button>:null}</div>})}</div>)}</div><p className="caption">Highest string at top · gold notes are roots · tap a note to hear it</p></div>}
function Chords({names}:{names:string[]}){return <div className="chordrow">{names.map(name=>{const c=chordShapes[name];return <div className="chordbox" key={name}><h4>{name}</h4><div className="chordfrets">{c.frets.map((f,i)=><span key={i}><small>{['E','A','D','G','B','e'][i]}</small><b>{f<0?'×':f}</b></span>)}</div><button className="textbtn" onClick={()=>playNotes(c.midi,180).catch(()=>{})}><Volume2 size={14}/> Hear chord</button></div>})}<p className="caption">Low E to high e · × = mute · 0 = open · numbers = frets. F uses a small four-string shape.</p></div>}
export default function Practice(){
 const [saved,setSaved]=useState<Saved>(initial),[loaded,setLoaded]=useState(false),[mode,setMode]=useState<'home'|'practice'|'warmup'>('home'),[notice,setNotice]=useState(''),[dialog,setDialog]=useState<'coach'|'settings'|null>(null),[hidden,setHidden]=useState(false),[hint,setHint]=useState(0),[bpm,setBpm]=useState(65),[metro,setMetro]=useState(false),[backing,setBacking]=useState(false),[accent,setAccent]=useState(true),[eighths,setEighths]=useState(false),[beat,setBeat]=useState(-1),[timer,setTimer]=useState(0),[timerOn,setTimerOn]=useState(false),[question,setQuestion]=useState(''),[chat,setChat]=useState<{role:'user'|'assistant';text:string}[]>([]),[busy,setBusy]=useState(false),[coachReady,setCoachReady]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null),savedRef=useRef(saved),audioCfg=useRef({bpm,metro,backing,accent,eighths,song:saved.song}),beatTimeouts=useRef<ReturnType<typeof setTimeout>[]>([]),tapTimes=useRef<number[]>([]);
 savedRef.current=saved;audioCfg.current={bpm,metro,backing,accent,eighths,song:saved.song};
 const song=songs[saved.song],track=saved.tracks[saved.song],position=track.position,lessonIndex=Math.floor(position/5),stepIndex=position%5,lesson=song.lessons[lessonIndex],quiz=mode==='practice'&&stepIndex===4;
 const current=mode==='warmup'?warmups[saved.warm]:lesson.steps[Math.min(stepIndex,3)],stepId=`${lessonIndex}-${stepIndex}`,done=track.completed.length;
 function changeTrack(fn:(t:Track)=>Track){setSaved(s=>({...s,tracks:{...s.tracks,[s.song]:fn(s.tracks[s.song])}}))}
 function quiet(){setMetro(false);setBacking(false);setTimerOn(false);stopDemo();document.querySelectorAll("audio").forEach(a=>a.pause());}
 function selectSong(id:SongId){quiet();setSaved(s=>({...s,song:id}));setHidden(false);setHint(0);setChat([]);}
 function jump(p:number){quiet();changeTrack(t=>({...t,position:p}));setMode('practice');setHint(0);setHidden(false);}
 function finish(review=false){quiet();if(mode==='warmup'){if(saved.warm===3){setSaved(s=>({...s,warm:0}));setMode('practice')}else setSaved(s=>({...s,warm:s.warm+1}));return}if(quiz&&(!lesson.quiz.every((q,i)=>track.answers[`${lessonIndex}-${i}`]===q.correct)||!track.playing[`${lessonIndex}`])){setNotice('Answer both questions correctly and complete the playing check first.');return}changeTrack(t=>({...t,completed:t.completed.includes(stepId)?t.completed:[...t.completed,stepId],review:review?[...new Set([...t.review,stepId])]:t.review.filter(x=>x!==stepId),position:Math.min(24,t.position+1)}));setHint(0);setHidden(false);if(position===24){setMode('home');setNotice('First five sessions complete. Revisit a lesson or try the other song.')}}
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(valid(parsed))setSaved(parsed)}}catch{setNotice('Progress could not be loaded. Use a backup if you have one.')}setLoaded(true);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});fetch('/api/coach').then(r=>r.json() as Promise<{ready?:boolean}>).then(d=>setCoachReady(!!d.ready)).catch(()=>{});},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(KEY,JSON.stringify(saved))}catch{setNotice('Progress cannot be saved on this device. Export a backup before leaving.')}},[saved,loaded]);
 useEffect(()=>{setBpm(track.tempos[stepId]||65);setTimer(0);setTimerOn(false);setHint(0);setHidden(false)},[saved.song,position,mode,saved.warm]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{if(!timerOn)return;const end=Date.now()+timer*1000;const t=setInterval(()=>{const remain=Math.max(0,Math.ceil((end-Date.now())/1000));setTimer(remain);if(!remain){setTimerOn(false);setNotice('Timer finished. Stay here or move on when ready.')}},250);return()=>clearInterval(t)},[timerOn]);
 useEffect(()=>{if(!metro&&!backing){setBeat(-1);return}let alive=true,interval:ReturnType<typeof setInterval>|undefined;context().then(ctx=>{if(!alive)return;let next=ctx.currentTime+.07,count=0;interval=setInterval(()=>{const cfg=audioCfg.current;while(next<ctx.currentTime+.12){const subdivisions=cfg.eighths?2:1,whole=count%subdivisions===0,barBeat=Math.floor(count/subdivisions)%4;if(cfg.metro)click(ctx,next,whole&&barBeat===0&&cfg.accent,whole?.18:.1);if(cfg.backing&&whole){const names=cfg.song==='royal'?['D','G']:['F','E♭'],chord=chordShapes[names[Math.floor(count/(subdivisions*4))%2]];chord.midi.forEach((n,i)=>tone(ctx,n,next+i*.008,.45,.045))}const delay=Math.max(0,(next-ctx.currentTime)*1000);if(whole){const timeout=setTimeout(()=>{if(alive)setBeat(barBeat)},delay);beatTimeouts.current.push(timeout)}next+=60/cfg.bpm/subdivisions;count++} },25)}).catch(()=>{setNotice('Tap start again to enable audio.');setMetro(false);setBacking(false)});return()=>{alive=false;if(interval)clearInterval(interval);beatTimeouts.current.forEach(clearTimeout);beatTimeouts.current=[];stopDemo()}},[metro,backing,eighths]);
 useEffect(()=>{const stop=()=>{if(document.hidden){quiet();}};document.addEventListener('visibilitychange',stop);return()=>document.removeEventListener('visibilitychange',stop)},[]);
 useEffect(()=>{const model=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!model)return;const lifecycle=new AbortController();try{model.registerTool({name:'read_practice_progress',description:'Read the current song and saved practice position.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const s=savedRef.current;return{song:s.song,position:s.tracks[s.song].position,completed:s.tracks[s.song].completed.length}}},{signal:lifecycle.signal})}catch{}return()=>lifecycle.abort()},[]);
 function tempo(v:number){const n=Math.max(35,Math.min(180,Math.round(v)));setBpm(n);if(mode!=='warmup')changeTrack(t=>({...t,tempos:{...t.tempos,[stepId]:n}}))}
 function tapTempo(){const now=performance.now();tapTimes.current=tapTimes.current.filter(x=>now-x<3000).concat(now).slice(-5);const a=tapTimes.current;if(a.length>1)tempo(60000/((a[a.length-1]-a[0])/(a.length-1)))}
 async function ask(text=question){if(!text.trim()||busy)return;setTimerOn(false);setMetro(false);setBacking(false);setBusy(true);setQuestion('');const next=[...chat,{role:'user' as const,text:text.trim()}];setChat(next);try{const r=await fetch('/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({song:saved.song,position,mode,warm:saved.warm,answers:track.answers,review:track.review,messages:next.slice(-8)})});const data=await r.json() as {answer:string;error?:string};if(!r.ok)throw Error(data.error||'The coach could not answer.');setChat([...next,{role:'assistant',text:data.answer}])}catch(e){setChat([...next,{role:'assistant',text:e instanceof Error?e.message:'Please try again.'}])}finally{setBusy(false)}}
 function exportProgress(){const url=URL.createObjectURL(new Blob([JSON.stringify(saved,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='guitar-practice-backup.json';a.click();URL.revokeObjectURL(url);setNotice('Backup exported.')}
 async function importProgress(file:File|undefined){if(!file)return;try{const d=JSON.parse(await file.text());if(!valid(d))throw Error();quiet();setSaved(d);setMode('home');setNotice('Progress restored.')}catch{setNotice('That file is not a valid practice backup.')}if(fileRef.current)fileRef.current.value=''}
 if(!loaded)return <main className="loading">Loading your practice…</main>;
 return <div className="app-shell" style={{'--song-color':song.color} as React.CSSProperties}>
 <header className="masthead"><a className="brand" href="#" onClick={e=>{e.preventDefault();quiet();setMode('home')}}><span className="brandicon"><Guitar size={24}/></span><span>Guitar Practice<small>MARK’S PRACTICE ROOM</small></span></a><button className="iconbtn" aria-label="Settings and backup" onClick={()=>setDialog('settings')}><Settings2 size={22}/></button></header>
 <main className="workspace">
 <aside className="song-panel"><span className="eyebrow">ON THE RECORD</span><Tabs value={saved.song} onValueChange={v=>selectSong(v as SongId)}><TabsList className="songtabs"><TabsTrigger value="royal">Royal</TabsTrigger><TabsTrigger value="hungersite">Hungersite</TabsTrigger></TabsList></Tabs>
 <div className="song-title"><span className="artist">GOOSE</span><h1>{song.name}</h1><p>{song.album}</p></div>
 <Progress value={done/25*100} className="course-progress"/><p className="progress-label">{done} of 25 steps complete</p>
 <div className="startbuttons"><button className="primary" onClick={()=>{setMode('practice');setHint(0)}}><Play size={18} fill="currentColor"/> {done===25?'Revisit practice':done?'Resume practice':'Start practice'}</button><button className="secondary" onClick={()=>{quiet();setMode('warmup')}}><Music2 size={18}/> 5-minute warmup</button></div>
 <p className="smallprint">Your place is saved. Stop whenever you like.</p>
 <nav className="lesson-nav" aria-label="Song sessions"><span className="eyebrow">YOUR SEQUENCE</span>{song.lessons.map((l,i)=>{const count=track.completed.filter(x=>x.startsWith(`${i}-`)).length;return <button key={i} className={mode!=='warmup'&&i===lessonIndex?'selected':''} onClick={()=>jump(i===lessonIndex?position:i*5)}><span className="lesson-number">{count===5?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><span>{l.title}<small>{count}/5 steps</small></span>{i===lessonIndex&&<span className="currentmark"/>}</button>})}</nav>
 <div className="references"><span className="eyebrow">SONG REFERENCES</span><a href={song.video} target="_blank" rel="noreferrer"><Play size={16}/> Video lesson <ExternalLink size={13}/></a><a href={song.pdf} target="_blank" rel="noreferrer"><BookOpen size={16}/> Reference tab PDF <ExternalLink size={13}/></a><p>Reference tabs are community transcriptions. Full solos are not included in this first course.</p></div></aside>
 <section className="practice-panel">
 {saved.song==='royal'&&<SongRecording onStart={()=>{setMetro(false);setBacking(false);stopDemo()}}/>}
 {mode==='home'?<><div className="panel-top"><span className="eyebrow">READY WHEN YOU ARE</span><span className="tag">ELECTRIC · STANDARD TUNING</span></div><div className="welcome"><h2>Your next<br/>good phrase.</h2><p>{lesson.goal}</p><button className="primary" onClick={()=>setMode('practice')}><Play size={18} fill="currentColor"/> {done?'Resume practice':'Begin session 1'}</button><span className="resume-caption">Session {lessonIndex+1} · {stepIndex===4?'Quick check':lesson.steps[stepIndex].title}</span></div><div className="home-cards"><div><Headphones size={24}/><h3>Listen. Find. Play.</h3><p>Small ear exercises connect sounds to your fingers.</p></div><div><BookOpen size={24}/><h3>Understand the notes.</h3><p>Learn the theory inside the music you want to play.</p></div></div><div className="context-card"><span className="eyebrow">THIS SONG’S STARTING POINT</span><p>{song.chordContext}</p></div>{track.review.length>0&&<div className="review-card"><h3>Worth another pass</h3>{track.review.map(id=>{const [l,s]=id.split('-').map(Number);return <button key={id} onClick={()=>jump(l*5+s)}>{song.lessons[l]?.steps[s]?.title||'Playing check'} <RotateCcw size={14}/></button>})}</div>}</>:
 <><div className="panel-top"><button className="textbtn" onClick={()=>{quiet();setMode('home')}}>Practice home</button><span className="tag">{mode==='warmup'?`WARMUP ${saved.warm+1}/4`:`SESSION ${lessonIndex+1} · STEP ${stepIndex+1}/5`}</span></div>
 <div className="exercise-heading"><span className="eyebrow">{quiz?'CHECK YOUR UNDERSTANDING':current.kind}</span><h2>{quiz?'A quick check.':current.title}</h2><p>{mode==='warmup'?'Prepare your hands. Your song progress stays where you left it.':lesson.goal}</p></div>
 {quiz?<div className="quiz">{lesson.quiz.map((q,i)=>{const chosen=track.answers[`${lessonIndex}-${i}`];return <fieldset key={i}><legend>{i+1}. {q.prompt}</legend>{q.options.map((option,j)=><button key={j} className={`answer ${chosen===j?(j===q.correct?'correct':'incorrect'):''}`} onClick={()=>changeTrack(t=>({...t,answers:{...t.answers,[`${lessonIndex}-${i}`]:j}}))}>{option}{chosen===j&&j===q.correct&&<Check size={18}/>}</button>)}{chosen!==undefined&&<p className="feedback">{chosen===q.correct?'Correct.':'Try again.'} {q.explain}</p>}</fieldset>})}<div className="playingcheck"><h3>Now play it</h3><p>{lesson.playing}</p><p className="caption">Self-assessment: the app is not listening to your guitar.</p><div className="buttonrow"><button className={track.playing[`${lessonIndex}`]==='ready'?'primary':'secondary'} onClick={()=>changeTrack(t=>({...t,playing:{...t.playing,[`${lessonIndex}`]:'ready'}}))}>Comfortable</button><button className={track.playing[`${lessonIndex}`]==='review'?'primary':'secondary'} onClick={()=>changeTrack(t=>({...t,playing:{...t.playing,[`${lessonIndex}`]:'review'}}))}>Needs another pass</button></div></div></div>:
 <><ol className="instructions">{current.instructions.map((x,i)=><li key={i}><span>{i+1}</span><p>{x}</p></li>)}</ol>
 {current.notes&&<><div className="diagram-head"><h3>Find your notes</h3><button className="textbtn" onClick={()=>setHidden(!hidden)}>{hidden?'Show labels':'Hide labels'}</button></div><Fretboard step={current} root={song.root} rootMidi={song.rootMidi} hidden={hidden}/></>}
 {current.audio&&<div className="audio-demo"><button className="secondary" onClick={()=>{setMetro(false);setBacking(false);playNotes(current.audio!,bpm).catch(()=>setNotice('Tap again to enable audio.'))}}><Volume2 size={18}/> Listen first</button><button className="textbtn" onClick={()=>{setMetro(false);setBacking(false);playNotes(current.audio!,Math.max(35,bpm*.65)).catch(()=>{})}}>Slower</button><button className="textbtn" onClick={stopDemo}>Stop</button><span className="caption">Synthesized note guide · original exercise</span></div>}
 {current.ear&&<div className="ear-card"><Headphones size={22}/><div><h3>Hear it before you see it</h3><p>Listen, hum, then find it on your guitar.</p><div className="buttonrow"><button className="secondary" onClick={()=>{setMetro(false);setBacking(false);playNotes(current.ear!,bpm).catch(()=>{})}}>Play mystery phrase</button><button className="textbtn" onClick={()=>setHint(Math.min(2,hint+1))}>{hint===0?'First hint':'Reveal notes'}</button></div>{hint>0&&<p className="hint">{hint===1?`First note: ${noteNames[current.ear[0]%12]}`:`Notes: ${current.ear.map(n=>noteNames[n%12]).join(' · ')}`}</p>}</div></div>}
 {current.chords&&<Chords names={current.chords}/>}
 <div className="theory-card"><BookOpen size={20}/><div><span className="eyebrow">WHY IT WORKS</span><p>{current.theory}</p></div></div><div className="target"><Check size={18}/><p><strong>Ready when you can:</strong> {current.target}</p></div>
 <div className="optional-timer"><button className="textbtn" onClick={()=>{if(timerOn)setTimerOn(false);else{if(!timer)setTimer((current.minutes||5)*60);setTimerOn(true)}}}><Timer size={16}/>{timerOn?'Pause timer':timer?'Resume timer':'Use optional timer'}</button>{timer>0&&<><span>{Math.floor(timer/60)}:{String(timer%60).padStart(2,'0')}</span><button className="textbtn" onClick={()=>{setTimerOn(false);setTimer(0)}}>Reset</button></>}</div></>}
 <div className="exercise-actions"><button className="secondary" onClick={()=>{quiet();setMode('home');setNotice('Your place is saved.')}}>Pause here</button>{!quiz&&<button className="textbtn" onClick={()=>{if(mode!=='warmup')changeTrack(t=>({...t,review:[...new Set([...t.review,stepId])]}));setNotice('Stay here for another pass.')}}><RotateCcw size={15}/> Another pass</button>}<button className="primary" onClick={()=>finish(quiz&&track.playing[`${lessonIndex}`]==='review')}><Check size={18}/>{mode==='warmup'&&saved.warm===3?'Resume practice':quiz?'Finish session':'Done / Next'}</button></div></>}
 </section>
 </main>
 <div className="tool-dock"><div className="metronome"><button className={`iconbtn ${metro?'active':''}`} aria-label={metro?'Stop metronome':'Start metronome'} onClick={()=>{if(!metro)document.querySelectorAll("audio").forEach(a=>a.pause());setMetro(!metro)}}>{metro?<Pause size={20}/>:<Play size={20}/>}</button><div className="bpm-display"><strong>{bpm}</strong><span>BPM</span></div><button className="tempo-adjust" aria-label="Decrease tempo" onClick={()=>tempo(bpm-5)}>−</button><Slider className="tempo-slider" value={[bpm]} min={35} max={180} step={1} onValueChange={v=>tempo(v[0])} aria-label="Tempo"/><button className="tempo-adjust" aria-label="Increase tempo" onClick={()=>tempo(bpm+5)}>+</button><button className="textbtn tap" onClick={tapTempo}>Tap</button><div className="beats" aria-label={`Beat ${beat+1}`}>{[0,1,2,3].map(i=><span key={i} className={beat===i?'lit':''}/>)}</div></div><div className="dock-extras"><button className={backing?'textbtn active':'textbtn'} onClick={()=>{if(!backing)document.querySelectorAll("audio").forEach(a=>a.pause());setBacking(!backing)}}><Music2 size={16}/> {backing?'Stop loop':'Backing loop'}</button><button className="coach-btn" onClick={()=>{setTimerOn(false);setDialog('coach')}}><MessageCircle size={18}/> Ask coach</button></div></div>
 {notice&&<div role="status" className="toast">{notice}</div>}
 <Dialog open={dialog!==null} onOpenChange={v=>{if(!v)setDialog(null)}}><DialogContent className="app-dialog"><DialogTitle>{dialog==='coach'?'Your practice coach':'Practice settings'}</DialogTitle><DialogDescription>{dialog==='coach'?`${song.name} · ${quiz?'Session check':current.title}`:'Your progress lives on this device. Export a backup before clearing website data.'}</DialogDescription>
 {dialog==='coach'?<><div className="coach-status">{coachReady?'Connected · current exercise included':'Coach setup pending · secure API key connection required'}</div>{!coachReady&&<p className="caption">Practice tools work without the coach. Do not enter an API key into this page.</p>}<div className="chatlog" aria-live="polite">{chat.length===0?<p>Ask about a note, chord, exercise, or a simpler way to practice. The coach cannot hear your guitar in this version.</p>:chat.map((m,i)=><div key={i} className={`chat-message ${m.role}`}><small>{m.role==='user'?'YOU':'COACH'}</small><p>{m.text}</p></div>)}{busy&&<p>Thinking…</p>}</div><div className="suggestions">{['Explain this theory simply','Give me an easier version','What should I listen for?'].map(x=><button key={x} disabled={!coachReady||busy} onClick={()=>ask(x)}>{x}</button>)}</div><form className="chatform" onSubmit={e=>{e.preventDefault();ask()}}><textarea value={question} onChange={e=>setQuestion(e.target.value)} maxLength={3000} placeholder="Ask about your practice…" aria-label="Question for coach" disabled={!coachReady}/><button className="primary" disabled={!coachReady||busy||!question.trim()} type="submit">Ask</button></form></>:<><div className="settingrow"><label htmlFor="accent">Accent beat one</label><Switch id="accent" checked={accent} onCheckedChange={setAccent}/></div><div className="settingrow"><label htmlFor="eighths">Eighth-note clicks</label><Switch id="eighths" checked={eighths} onCheckedChange={setEighths}/></div><p className="caption">Keep the app open for audio. Switching apps or locking your phone stops playback.</p><label className="noteslabel" htmlFor="notes">Practice notes</label><textarea id="notes" value={saved.notes} onChange={e=>setSaved(s=>({...s,notes:e.target.value}))} maxLength={6000} placeholder="Something to remember next time…"/><div className="buttonrow"><button className="secondary" onClick={exportProgress}><Download size={16}/> Export progress</button><button className="secondary" onClick={()=>fileRef.current?.click()}><Upload size={16}/> Restore backup</button><input type="file" accept="application/json,.json" hidden ref={fileRef} onChange={e=>importProgress(e.target.files?.[0])}/></div><div className="install-help"><h3>Put it on your iPhone</h3><p>Open in Safari, tap Share, then Add to Home Screen. Enable Open as Web App if offered.</p><p className="caption">Lessons and synthesized audio can work offline after loading. Reference videos, PDFs, and the coach need internet.</p></div></>}
 </DialogContent></Dialog>
 </div>
}
