export type SongId = 'royal' | 'hungersite';
export type Step = { title: string; kind: string; instructions: string[]; target: string; theory: string; notes?: number[]; degrees?: string[]; audio?: number[]; ear?: number[]; chords?: string[]; minutes?: number };
export type Question = { prompt: string; options: string[]; correct: number; explain: string };
export type Lesson = { title: string; goal: string; steps: Step[]; quiz: Question[]; playing: string };
export type Song = { name: string; album: string; root: string; rootMidi: number; color: string; pdf: string; video: string; chordContext: string; lessons: Lesson[] };
const step = (title:string,kind:string,instructions:string[],target:string,theory:string,rest:Partial<Step>={}):Step=>({title,kind,instructions,target,theory,minutes:5,...rest});
const q=(prompt:string,options:string[],correct:number,explain:string):Question=>({prompt,options,correct,explain});
function lessons(id:SongId):Lesson[]{
 const royal=id==='royal', root=royal?'D':'F', third=royal?'F♯':'A', fifth=royal?'A':'C', base=royal?62:65;
 const tones=[base,base+4,base+7], pent=[base,base+2,base+4,base+7,base+9,base+12];
 const other=royal?'G':'E♭';
 return [
 {title:'Find the song’s home',goal:`Hear ${root}, locate it on your guitar, and begin a simple rhythm part.`,steps:[
 step('Listen to the reference','Listen',[`Open the matching lesson video below. Listen to the opening and notice when the phrase repeats.`,`Hum a short fragment before touching the guitar. You’re listening for shape and rhythm; exact notes can wait.`],'You can hum a small fragment and recognize its repeat.','Listening gives the finger movements a musical destination.'),
 step(`Find ${root} on the fretboard`,'Fretboard',[`Tap “Listen first” for a ${root} reference note. Hum it, then find the highlighted notes.`,`Play each highlighted ${root}. These are the same note name in different octaves.`,`Hide the labels and find the roots again.`],`Find three ${root} notes without the labels.`,'An octave changes pitch height while preserving the note name.',{notes:[0],degrees:['1'],audio:[base,base+12]}),
 step(`Build a ${root}–${other} loop`,'Rhythm',[`Use the chord shapes shown below. Play one chord per bar: ${root} for four beats, then ${other} for four beats.`,`Count “1, 2, 3, 4” and use the metronome if helpful. Stop notes cleanly.`,`Record four bars on your looper, or use “Backing loop.” This is a simplified practice vamp, not the song’s full arrangement.`],'Repeat four bars without losing the count.','A steady rhythm part gives your lead phrases a context.',{chords:[root,other]}),
 step('Answer with one note','Ear & music',[`Listen to the reference ${root}; hum it, then play it.`,`Over your loop, play only ${root}. Create two different rhythms with that same note.`,`Leave a full bar of silence between your phrases.`],'Play two distinct rhythms and leave intentional space.', 'Rhythm and silence make musical ideas even with one pitch.',{audio:[base],ear:[base],notes:[0],degrees:['1']})],
 quiz:[q('What changes when you play the same note an octave higher?',['Its note name','Its pitch height','The song’s tempo'],1,'The pitch rises, but the note name stays the same.'),q('What is the main purpose of the loop in this exercise?',['A steady harmonic and rhythmic context','Playing as fast as possible','Replacing all the song’s chords'],0,'The simplified loop supports practice; it is not a complete arrangement.')],playing:`Find a ${root} and play a short rhythm over the loop.`},
 {title:'Hear the chord inside the melody',goal:`Connect ${root}, ${third}, and ${fifth} to a major chord.`,steps:[
 step('Recall your root','Recall',[`Find three ${root} notes before revealing labels.`,`Play your rhythm loop again, keeping the count even.`],'Find the notes from memory, then check.','Recall comes before adding new material.',{notes:[0],degrees:['1'],audio:[base]}),
 step('Meet the major triad','Theory in your hands',[`Play the highlighted notes: ${root}, ${third}, ${fifth}.`,`Say “root, third, fifth” as you play. Listen to the original demonstration.`,`Play them ascending and descending without hurrying.`],'Identify each of the three chord tones.',`${root} major contains ${root} (root), ${third} (major third), and ${fifth} (perfect fifth).`,{notes:[0,4,7],degrees:['1','3','5'],audio:tones}),
 step('Hear, hum, find','Ear training',[`Listen to the mystery phrase before revealing the notes.`,`Hum it, then find it using only the root, third, and fifth.`,`Use a hint when needed; replay until you can match the order.`],'Match a three-note phrase by ear before checking.','A small set of choices helps connect your ear to the fretboard.',{notes:[0,4,7],degrees:['1','3','5'],ear:[base+7,base+4,base]}),
 step('Choose a landing note','Make music',[`Use your backing loop, but focus on the bars with ${root} underneath.`,`Make short phrases and end first on ${root}, then on ${third}, then on ${fifth}.`,`Listen to the different endings. Don’t assume a chord tone has the same role over the other chord.`],'Make three phrases with three different ending notes.','A note’s role depends on the chord sounding underneath.',{notes:[0,4,7],degrees:['1','3','5'],audio:[base+7,base+4,base],chords:[root,other]})],quiz:[q(`Which notes form ${root} major?`,[`${root}, ${third}, ${fifth}`,`${root}, ${royal?'F':'A♭'}, ${fifth}`,`${root}, ${royal?'E':'G'}, ${fifth}`],0,'A major triad contains a root, major third, and perfect fifth.'),q('Does a note keep the same chord role when the backing chord changes?',['Always','Not necessarily','Only at a faster tempo'],1,'Its relationship is measured against the current chord, so its role can change.')],playing:`Play ${root}–${third}–${fifth} and name their roles.`},
 {title:'Build a lead vocabulary',goal:'Use a major pentatonic shape and make phrases with rhythm and space.',steps:[
 step('Recall chord tones','Recall',[`Play ${root}, ${third}, and ${fifth}.`,`Hide the labels and find a root, third, and fifth in the displayed area.`],'Recall three chord tones without help.','Chord tones are landmarks within a larger scale.',{notes:[0,4,7],degrees:['1','3','5']}),
 step(`${root} major pentatonic`,'Scale',[`Play the highlighted notes slowly, one string at a time.`,`The five degrees are 1, 2, 3, 5, 6. The audio gives a one-octave example; the diagram repeats them across strings.`,`Use small, relaxed picking movements and mute strings you’re not playing.`],'Play a short ascending and descending fragment cleanly.','Major pentatonic has five notes. It is a starting vocabulary, not a rule that every song note must follow.',{notes:[0,2,4,7,9],degrees:['1','2','3','5','6'],audio:pent}),
 step('Learn an original practice phrase','Listen & play',[`Listen to the example. Hum it, then find the notes in the diagram.`,`This is an original exercise: 5–3–2–1, followed by a rest. It is not a transcription of the song’s solo.`,`Repeat with a longer final root, then change the rhythm.`],'Play the phrase from memory in two rhythms.','Repeated notes and patterns become vocabulary when you vary their timing.',{notes:[0,2,4,7,9],degrees:['1','2','3','5','6'],audio:[base+7,base+4,base+2,base]}),
 step('Question and answer','Improvisation',[`Play a phrase of three to five notes over the loop.`,`Leave space, then answer it with the original practice phrase.`,`Focus first on ${root} bars; listen carefully when the chord changes.`],'Play two rounds of question, silence, and answer.','Phrasing gives a solo structure beyond running up and down a scale.',{notes:[0,2,4,7,9],degrees:['1','2','3','5','6'],chords:[root,other]})],quiz:[q('Which degrees make a major pentatonic scale?',['1, ♭3, 4, 5, ♭7','1, 2, 3, 5, 6','1, 2, 3, 4, 5, 6, 7'],1,'Major pentatonic uses 1, 2, 3, 5, and 6.'),q('How can the same notes become a different phrase?',['Change the rhythm and pauses','They cannot','Always add more notes'],0,'Timing, emphasis, and silence can transform the same pitches.')],playing:'Play a short phrase, pause, and answer it.'},
 {title:'Learn a piece of the real riff',goal:'Use the reference tab and recording to connect a short song phrase with its theory.',steps:[
 step('Hear the real phrase','Song study',[`Open the lesson video and the reference PDF. Choose only the first small phrase of the main riff.`,`Replay the instructor’s demonstration. Hum it and tap its rhythm.`,`Use the album version identified in the PDF as your reference; live versions can differ.`],'Recognize and hum the chosen phrase.','The source tab is a reference to check against the recording, not a guarantee of perfect accuracy.'),
 step('Try it before revealing the tab','Ear training',[`Search for the phrase’s first note on the guitar.`,`Try the next two or three notes. Stay with a tiny fragment.`,`If stuck, look at the first fret in the PDF, then return to listening.`],'Find at least a small part by ear, using hints as needed.','Transcribing a few notes is a useful step toward a longer solo.'),
 step('Check and understand','Tab & theory',[`Compare your attempt with that section of the PDF and lesson.`,`Name the notes from their string and fret; locate them on the diagram.`,`Identify the backing chord at that moment before calling a note its root, third, or fifth. Ask the coach with the notes and chord, or use the theory card.`],'Name two notes and explain their relationship to the backing chord.',royal?'The chart’s intro uses D, G/B, and C. G/B means a G major chord with B as its lowest note; it is not a new scale.':'The chart’s verse uses F and E♭. If F is the tonal center, E♭ is the flattened seventh degree: a useful introduction to Mixolydian color.',{notes:[0,2,4,5,7,9,10],degrees:['1','2','3','4','5','6','♭7']}),
 step('Play and change one thing','Apply',[`Play the small riff fragment slowly with the reference demonstration.`,`Repeat it until the note endings and rhythm are controlled.`,`Make a variation by changing only the rhythm, keeping the notes.`],'Play the fragment and one intentional variation.','Learning a phrase and transforming it helps you use the idea outside the song.')],quiz:[royal?q('What does G/B mean?',['G major with B in the bass','G minor followed by B major','A B chord with no third'],0,'The letter after the slash specifies the bass note.'):q('Relative to F, what degree is E♭?',['Major seventh','Flattened seventh','Major third'],1,'F’s major seventh is E; lowering it one semitone gives E♭.'),q('What do you need to establish a melody note’s chord role?',['The chord sounding at that moment','Only the fret number','Only the song title'],0,'The backing chord provides the root against which that note is measured.')],playing:'Play your short reference fragment, then change its rhythm.'},
 {title:'Make it your own',goal:'Combine rhythm, a song phrase, and an original answer; choose the next review.',steps:[
 step('Recall without the diagram','Recall',[`Find the root and major third.`,`Play yesterday’s song fragment from memory, then check the source.`],'Recall landmarks and the small riff fragment.', 'Review checks what you can retrieve, rather than only what looks familiar.',{notes:[0,4,7],degrees:['1','3','5']}),
 step('Connect rhythm and lead','Coordination',[`Play two bars of the simple chord vamp, then two bars of a short lead phrase.`,`Keep counting through the switch.`,`Alternatively, let the backing loop play and enter on beat one.`],'Switch between rhythm and a phrase without losing the pulse.', 'Lead playing shares the same underlying pulse as rhythm guitar.',{chords:[root,other],audio:[base,base+4,base+7,base+4]}),
 step('Build a small solo','Creative practice',[`Use your song fragment as a call. Leave space and answer with an original phrase.`,`Repeat with one change in rhythm or picking strength.`,`Stay with a small vocabulary and listen to the backing chords.`],'Play a repeatable musical idea with a clear answer.', 'A coherent short idea is a meaningful first solo; complexity can grow later.',{notes:[0,2,4,7,9],degrees:['1','2','3','5','6'],chords:[root,other]}),
 step('Listen back and choose a review','Reflection',[`Optionally record 20–30 seconds with Voice Memos or your looper.`,`Listen for one thing: timing, string noise, or clear pauses.`,`Use “Another pass” on any exercise you want to revisit. Longer solo transcription is a later goal; this course does not include a verified full solo.`],'Identify one strength and one specific thing to revisit.', 'Listening back makes your next practice choice concrete.')],quiz:[q('Which is the most useful next practice goal?',['Play everything faster','Fix one specific issue you can hear','Learn all five positions immediately'],1,'A specific issue gives you an actionable next step.'),q('What makes a short solo feel coherent?',['Repetition, variation, and phrasing','Using every scale note','Never pausing'],0,'Related ideas and deliberate space can give a solo a clear shape.')],playing:'Play a short call-and-response idea over your loop.'}
 ];
}
export const songs:Record<SongId,Song>={
 royal:{name:'Royal',album:'Chain Yer Dragon',root:'D',rootMidi:62,color:'#f5ae64',pdf:'https://goosethebandtabs.wordpress.com/wp-content/uploads/2025/08/royal-chainyerdragon-mainparts-updated.pdf',video:'https://www.youtube.com/watch?v=kglzvEgm8eg',chordContext:'Reference chart: intro D–G/B–C; other sections introduce more chord changes. Begin with a simplified practice vamp.',lessons:lessons('royal')},
 hungersite:{name:'Hungersite',album:'Dripfield',root:'F',rootMidi:65,color:'#87cbd1',pdf:'https://goosethebandtabs.wordpress.com/wp-content/uploads/2022/04/hungersite.pdf',video:'https://www.youtube.com/watch?v=2ki4rZv9k4E',chordContext:'Reference chart: verse F–E♭. Major pentatonic supplies a starting vocabulary; the full song includes other harmonic colors.',lessons:lessons('hungersite')}
};
export const warmups:Step[]=[
 step('Relaxed alternate picking','Warmup',['Alternate down/up on one open string. Keep the motion small, shoulders relaxed, and notes even.'],'Play evenly with a relaxed hand.','Warmup should feel easy; slow down whenever you tense up.',{minutes:1}),
 step('Finger coordination','Warmup',['Play frets 5–6–7–8 with fingers 1–2–3–4 on one string, then neighboring strings. Use a comfortable hand position.'],'Move smoothly without squeezing or forcing a stretch.','Use only as much pressure as the note needs. Stop if playing hurts.',{minutes:2}),
 step('Clean string crossings','Warmup',['Alternate between two neighboring strings. Listen for unused strings ringing and gently mute them.'],'Hear only the notes you intend to play.','Clean note endings matter as much as clean starts.',{minutes:1}),
 step('Play something familiar','Warmup',['Play a familiar riff or chord progression gently. Let your hands settle into playing.'],'Feel ready to begin or resume.','Your lesson position stays unchanged during warmup.',{minutes:1})
];
export const noteNames=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'];
export const chordShapes:Record<string,{frets:number[];midi:number[]}>={D:{frets:[-1,-1,0,2,3,2],midi:[50,57,62,66]},G:{frets:[3,2,0,0,0,3],midi:[43,47,50,55,59,67]},F:{frets:[-1,-1,3,2,1,1],midi:[53,57,60,65]},'E♭':{frets:[-1,-1,1,3,4,3],midi:[51,58,63,67]}};
