import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {songs,warmups,SongId} from '@/lib/curriculum';
const limits=new Map<string,{count:number;until:number}>();
function config(){return env as unknown as {OPENAI_API_KEY?:string;OPENAI_MODEL?:string}}
export async function GET(){const e=config();return Response.json({ready:!!(e.OPENAI_API_KEY&&e.OPENAI_MODEL)},{headers:{'Cache-Control':'no-store'}})}
export async function POST(request:Request){
 const e=config();if(!e.OPENAI_API_KEY||!e.OPENAI_MODEL)return Response.json({error:'The coach is not connected yet. Your lessons, quizzes, and audio still work. Secure API setup is the remaining step.'},{status:503});
 const user=await getChatGPTUser();if(!user)return Response.json({error:'Please sign in to use your practice coach.'},{status:401});
 if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Request origin not allowed.'},{status:403});
 const length=Number(request.headers.get('content-length')||0);if(length>24000)return Response.json({error:'Please shorten your question.'},{status:413});
 let d;try{const raw=await request.text();if(raw.length>24000)throw Error();d=JSON.parse(raw)}catch{return Response.json({error:'Invalid question.'},{status:400})}
 if(!['royal','hungersite'].includes(d.song)||!Number.isInteger(d.position)||d.position<0||d.position>=25||!Array.isArray(d.messages)||d.messages.length<1||d.messages.length>8||!d.messages.every((m:{role:string;text:string})=>m&&['user','assistant'].includes(m.role)&&typeof m.text==='string'&&m.text.length<=4000))return Response.json({error:'Invalid practice context.'},{status:400});
 const now=Date.now(),limit=limits.get(user.userId);if(limit&&limit.until>now&&limit.count>=20)return Response.json({error:'You’ve reached the coach’s hourly request limit. Continue practicing and try again later.'},{status:429});limits.set(user.userId,{count:limit&&limit.until>now?limit.count+1:1,until:limit&&limit.until>now?limit.until:now+3600000});
 const song=songs[d.song as SongId],lesson=song.lessons[Math.floor(d.position/5)],step=d.mode==='warmup'?warmups[Math.max(0,Math.min(3,Number(d.warm)||0))]:lesson.steps[d.position%5];
 const instructions=`You are a patient electric-guitar teacher for Mark, an experienced chord player learning lead guitar and theory. Be concise and concrete. Current song: ${song.name}; album ${song.album}. ${song.chordContext} Current lesson: ${lesson.title}. Current exercise: ${JSON.stringify(step||lesson.quiz)}. Self-reported review: ${JSON.stringify(d.review||[]).slice(0,1000)}. Quiz choices: ${JSON.stringify(d.answers||{}).slice(0,1000)}. Distinguish sourced song facts from original exercises and interpretation. You have not heard the student's playing. Do not claim automatic listening, exact solo transcription, or access to a tab or video not supplied. Explain note roles relative to the current backing chord. Offer a small playable next step. Do not rewrite their whole curriculum. Never request an API key. Avoid full copyrighted tabs or lyrics. No external tools are available.`;
 try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${e.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:e.OPENAI_MODEL,instructions,input:d.messages.map((m:{role:string;text:string})=>({role:m.role,content:m.text})),max_output_tokens:700,store:false}),signal:AbortSignal.timeout(45000)});if(!r.ok)return Response.json({error:r.status===429?'The AI service is busy or has reached its account usage limit. Please try later.':'The coach connection needs attention. Please check the configured model and API access.'},{status:502});const body=await r.json() as {output?:{content?:{type:string;text?:string}[]}[]};const answer=body.output?.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text||'').join('\n');if(!answer)throw Error();return Response.json({answer},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'The coach could not respond. Please try again.'},{status:502})}
}
